### ISSUE TITLE
Odd empty state

### ISSUE THREAD

**Issue by bertob** [lakoliu/Furtherance#1]
The current empty state is trying to do two things at once, and a bit awkward as a result. At the top there's the normal timer and new task entry, but below that there's also an empty/welcome state with usage instructions. The result is a bit confusing:

![image](https://user-images.githubusercontent.com/1908896/160940930-3de00750-323c-4c11-962f-393b3b237c0a.png)

IMO the app is simple enough that it doesn't necessarily need instructions, the timer/entry/button stuff at the top would be enough as an empty state by itself, if it was vertically centered. An example of something similar is the  "Stopwatch" view in GNOME Clocks, where the timer is centered vertically until you add the first lap and then becomes top-aligned. I think the same thing would work well here.

**Comment by Mo8it** [comment]
Personally, I like the welcome window. I only found the plus icon confusing because I thought I have to add something pressing some plus button.

**Comment by lakoliu** [comment]
Cool, thanks for your input @Mo8it!

**Comment by bertob** [comment]
If you do end up keeping the welcome view I'd recommend integrating the entry into that flow, by moving it below the instructions (and dropping the timer), so the reading direction goes smoothly from welcome to the first action. Otherwise the layout has two focal points, and you don't know where to start.

**Comment by lakoliu** [comment]
Finally decided to change this! The empty state is now a centered timer/input which moves up when the first task is saved. Thanks for the recommendation @bertob!
