### ISSUE TITLE
Overview: task names are truncated – increasing max width of list?

### ISSUE THREAD

**Issue by lightonflux** [lakoliu/Furtherance#102]
Hi, i am using the app in German, and often the task names are a bit longer. 
Especially if i have task with German project names in them (compound words!) . Currently, that means that over 80% of my recent entries are truncated in the overview/main view. And it's hard to differentiate tasks. Neither "$action $project" nor "$project $action" works well for task names in this case. 

Would it be possible to increase the max width of the list. Not necessarily the window size, but the width of the list, so it can display longer names if the user resizes the window. 

I looked through old issues, and it seems this kind of change should not impact mobile (#85) as the default window size should remain the same size and the minimum width is not affected at all.

**Comment by lightonflux** [comment]
Comparison to gnome-control-center:

# Small (mobile)
![Bildschirmfoto vom 2023-01-18 19-02-19](https://user-images.githubusercontent.com/1377943/213259396-f789d469-af31-43fe-92a4-7e4318405812.png)

# Wide (desktop)
![Bildschirmfoto vom 2023-01-18 19-02-35](https://user-images.githubusercontent.com/1377943/213259428-2ed6cf7b-bd9a-464e-99ce-2d387e9538bb.png)

**Comment by lakoliu** [comment]
Hi @lightonflux, thanks for your recommendation! I think this is a good idea, and probably should have been done from the beginning. I will work on making the input box and list expand when the window expands and hopefully get it out in the next update. I'm busy with another project right now, so it may not be immediate, but I'll try to get it done soon.

**Comment by lakoliu** [comment]
This should be fixed in let imp eda4e51. The task rows don't expand infinitely like the task input bar does, which I think is a limitation/feature of AdwPreferencesPage, but someone can correct me if I'm wrong there. 

Hope this helps! It will be in the next release. Sorry it took me so long!
