### ISSUE TITLE
total task time in CSV

### ISSUE THREAD

**Issue by tobehn** [lakoliu/Furtherance#105]
Basically i need to export a monthly report of all my tasks. Filter them by #tag, sum up total time and then i am able to write a monthly invoice of my hours. 

Currently it is not possible to calculate the times in the exported CSV for each #tag i gave the task.

Is it possible to export an **additional column** with the **total seconds of each task**. 
I could then easily calculate all the times I need. 

ALTERNATIVE:
in the report feature you have already implemented all the filtering by tags and time. 
It would be awesome if i could print/export a report of a certain #tag based on chosen time.

**Comment by lakoliu** [comment]
I will look into doing one of these and hopefully get it implemented soon (within the next month or so, I'm working on another project atm). My first thought is that exporting the reports will be the best way, but I will definitely look into adding a total seconds column in the CSV as well.

**Comment by lakoliu** [comment]
05ba763 adds total seconds to the CSV. This will be in the next release (coming very soon, not like last time, promise!  :laughing:)
I also added "print/export reports" to the to-do list.
