### ISSUE TITLE
Is it normal when I set a Pomodoro Timer, it appears a minute over instead of the time I set?

### ISSUE THREAD

**Issue by kanansnote** [lakoliu/Furtherance#107]
For instance, it will display as 26 minutes if I set a timer for 25. I'm not sure whether it's a bug, just wondering if there's anything you should fix here. Thanks.

By the way, the app version is 1.7.0 and the app package is flatpak.

**Comment by lakoliu** [comment]
No, that should not be the case. I will check it out get it fixed as soon as possible. Thanks for letting me know!

**Comment by lakoliu** [comment]
Sorry for the late response, I just got the time to look into this.
Does this happen every time? What distro and desktop environment are you using? I can't seem to replicate it.

**Comment by kanansnote** [comment]
Ubuntu 23.04, GNOME 44

It happens exactly when you add or subtract a minute to the timer. The problem then goes away when you restart the app or simply start the timer:


https://github.com/lakoliu/Furtherance/assets/99095303/658db802-59d9-4d37-a588-3d17496f7e7d
