### ISSUE TITLE
Display total week time

### ISSUE THREAD

**Issue by corebots** [lakoliu/Furtherance#112]
It would be nice to separate the ways by sort of a separator/spacer showing the total week time, on the top for the current week. That way one gets an overview for the whole week, also immediately sees how much time is still missing to the target. See what Clockify does for an example
![image](https://github.com/lakoliu/Furtherance/assets/12252430/2d0ce833-8dda-4c02-840c-beecf30624ca)

**Comment by lakoliu** [comment]
In reports you should now be able to select "This Week" to see the total time so far this week. You can also filter that by tasks and tags.
