### ISSUE TITLE
Error connected to Furtherance: "org.gnome.Platform//43 is end-of-life"

### ISSUE THREAD

**Issue by dotedus** [lakoliu/Furtherance#119]
I am relatively new to open source apps, and I see this warning in the terminal now when updating in Linux Mint.  Do I wait for the developers to update the app to work with the next supported runtime, or do I have to update that myself?

**Comment by adrinux** [comment]
You wait...or you  get involved to help - but you'd need to be a programmer to do that. The application will need to be partially rewritten to work with the Gnome 44 or 45 runtime. I'm not much of a programmer and not familiar with the Furtherance code base, but this sort of thing is often a major undertaking, it may be some time before that error goes away.

The software will continue work however.

**Comment by lakoliu** [comment]
Thank you for bringing this to my attention. I will work on getting this updated ASAP.
