### ISSUE TITLE
Add hint about right mouse click

### ISSUE THREAD

**Issue by Mo8it** [lakoliu/Furtherance#12]
Pressing the right mouse button on a recent task starts the timer with it. This feature is definitely needed, but there is no hint about it. I just discovered it by random clicking.

**Comment by lakoliu** [comment]
Yes, I had a feeling someone would open an issue about this. I've had the exact same thought, but I haven't decided on a good way to let people know about it. Perhaps I will add it to the start page, before any tasks are in the list. Any ideas would be appreciated. I will update this issue when it is fixed.

**Comment by Mo8it** [comment]
A much better way would be to add a button! You replace the current functionality of the right click now with a button on the right side of each task. Just use the button for starting the timer that you already have and add it to every task on the right side.

**Comment by lakoliu** [comment]
Agreed, that would be a good way to do it. My original reasoning not to do this was I thought it would look too cluttered. For now I will add a hint and then I will test what a button would look like next to every task.

**Comment by lakoliu** [comment]
Commit af3f7b2 adds a button as suggested to restart a task with the same name and tags. The right mouse button still works as well for now.
