### ISSUE TITLE
Support Apple Shortcuts

### ISSUE THREAD

**Issue by TribuneX** [lakoliu/Furtherance#125]
I have my time tracking automated with a combination of [iOS Focus](https://support.apple.com/en-gb/guide/iphone/iphd6288a67f/ios) and [Shortcuts](https://support.apple.com/en-gb/guide/shortcuts/welcome/ios).

I start and stop timers e.g. based on opening certain Apps (mostly 2FA VPN apps of my clients).
These automations trigger timers (currently with [Tyme](https://www.tyme-app.com/en/shortcut-documentation/)).

It would be awesome if Tie Tracker could at least offer basic shortcuts for starting and stopping certain timers.

**Comment by rickykresslein** [comment]
Thanks for the suggestion! I think this would be an excellent feature for Furtherance iOS and I will add it to the list.

**Comment by lakoliu** [comment]
The latest version of Furtherance for macOS and iOS now has support for Shortcuts and Siri commands! Thanks for the suggestion.
