### ISSUE TITLE
Crash after using Pomodoro mode

### ISSUE THREAD

**Issue by codeologylab** [lakoliu/Furtherance#127]
OS: Fedora 38 (6.6.7-100.fc38.x86_64)
Gnome version: 44.7
Windowing system: Wayland
Furtherance version: 1.8.2 installed via Flathub

How to reproduce: 

1. Enable Pomodoro mode with a default setting of 25 minutes;
2. Start a session countdown and wait till it completes;
3. Click on the restart icon of the same task to restart another countdown;
4. Application crashes and quits.

**Comment by rickykresslein** [comment]
Found the bug and got it fixed with commit 3157cd4. It will be in the next release, which I will try to get out very soon. Thanks again for reporting this.
