### ISSUE TITLE
Right click incorrect time assignment

### ISSUE THREAD

**Issue by Mo8it** [lakoliu/Furtherance#13]
When the time tracker is running for a task, clicking on another recent task stops the timer and adds the time to the second task!

Reproduce:
- Start Task1
- Stop Task1
- Start Task2
- Stop Task2
- Start Task1
- Wait for some seconds
- Right click on Task2 -> The timer stops and the time spent is added to Task2, not Task1!

Expected:
On right click on Task2 while Task1 is running, Task1 should stop, add the time spent to Task1 and then Task2 should start.

**Comment by lakoliu** [comment]
Good catch! I hadn't noticed that. I will get to work fixing this right away. Thank you!

**Comment by lakoliu** [comment]
As with Issue #14, to right-click a task to duplicate it the timer now needs to be stopped.
