### ISSUE TITLE
Expand width of tasks as window expands 

### ISSUE THREAD

**Issue by one2three4f** [lakoliu/Furtherance#132]
I think the width of tasks should continue to grow and correspond to window size, curious about your thoughts on this. If it's overly opinated, maybe a setting for the user to decide?

[Screencast from 2024-02-16 09-06-39.webm](https://github.com/lakoliu/Furtherance/assets/143331948/212cfeda-c46e-4333-8b9a-53a5fdd61e69)

**Comment by rickykresslein** [comment]
I think you're right, I think letting the user decide by adjusting the window is the way to go. Thanks for your input. I'll look into doing this as soon as I get some time.

**Comment by lakoliu** [comment]
After looking into this more, the task rows in Furtherance are based on libadwaita/gtk4's preferences row, which gives them their style. This max width seems to be a limitation of those widgets. You can see this in the Gnome Settings - the individual item rows never get larger than the same width they get to in Furtherance. Maybe this will change upstream at some point, but for now I don't plan on creating a new type of widget just so these rows expand. Sorry!
