### ISSUE TITLE
Delete 00:00:00 task

### ISSUE THREAD

**Issue by sharma-shray** [lakoliu/Furtherance#139]
maybe it would be better to delete tasks with 0 seconds of duration
![image](https://github.com/lakoliu/Furtherance/assets/48922607/b2047c08-8d80-4d84-aee2-42781a96927e)
![image](https://github.com/lakoliu/Furtherance/assets/48922607/33fabb59-1e07-4cf7-806c-981b0dbf020d)

**Comment by lakoliu** [comment]
Thank you for the suggestion, but I won't be implementing this. I can see how it could be nice, but if a user wants to start and stop a task immediately for whatever reason, I think they should be able to do that. If it was an accident, it is pretty simple to delete manually.
