### ISSUE TITLE
Right click deleting task

### ISSUE THREAD

**Issue by Mo8it** [lakoliu/Furtherance#14]
Related to https://github.com/lakoliu/Furtherance/issues/13

When starting a new timer and not stopping it, right clicking on a recent task adds the time spent to this recent task which is described in the other issue.

But this issue is about the new task being deleted.

Reproduce:
- Start Task1
- Stop Task1
- Start Task2 which is NOT in the recent tasks
- Right click on Task1 -> The time spent is added to Task1 and Task2 is deleted. It does not appear in recent tasks.

Expected:
On right click on Task1, Task2 should stop, add the time spent to Task2 and Task2 should be added with this time to recent tasks. Then Task1 should start.

**Comment by lakoliu** [comment]
Much appreciated; this will be fixed with Issue #13.

**Comment by lakoliu** [comment]
With commit 3481463 I made it so it is no longer possible to right-click a task to "duplicate" it. The timer has to be stopped. This is not exactly your "expected behavior", however for now I believe it is the best way to resolve this. I may consider changing the behavior in the future.
