### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Mo8it** [lakoliu/Furtherance#15]
I am on Gnome and not getting system notifications after being idle. I am only getting a popup from the window. But if the window is hidden or covered, this is not helpful.

Expected:
After being idle, send a system notification with the question about dismissing or continuing. "Dismiss" and "Continue" should be two notification buttons.

**Comment by lakoliu** [comment]
That's a good idea to send a system notification. I haven't ran into the issue yet that the popup doesn't appear over my other windows, so I'll look into that as well.

**Comment by lakoliu** [comment]
I'm happy to report that I just got finished adding system notifications on idle that have buttons to allow you to continue or discard the idle time! This feature will be in the next release. Thanks for the suggestion!
