### ISSUE TITLE
Display the running timer/task in the desktop top bar

### ISSUE THREAD

**Issue by GuillaumeAmat** [lakoliu/Furtherance#19]
I often forget to stop/start my timers and I think it would be a good reminder to have it display in the desktop top bar (e.g.: top black bar on GNOME).

It's also useful to see the ongoing task duration without having to find Furtherance's window (e.g.: during screen sharing).

I know that the suggested placement is GNOME related... But I think you get the point :ok_hand: 

Thanks again for that great and simple app!

**Comment by lakoliu** [comment]
Thank you for the suggestion, I will definitely consider this. The main thing holding me back at the moment is that GNOME doesn't really like tray icons and they require installing an extension to see them. But I do think it would be a handy feature.

**Comment by lakoliu** [comment]
I've looked into this a bit and from what I can find AppIndicators are completely deprecated in GTK 4 and GNOME doesn't want you to use them. To make them work, not only does the user need to install an extension, but I'd also need to add some GTK 3 stuff to Furtherance, which I don't want to do. I'm going to close this issue for now as it is not viable, but if GNOME or GTK decides to make app indicators a thing again I will definitely implement them. Thanks again for the suggestion!

**Comment by GuillaumeAmat** [comment]
Thank you for the investigation, it's greatly appreciated :pray:

**Comment by salim-b** [comment]
> I've looked into this a bit and from what I can find AppIndicators are completely deprecated in GTK 4 and GNOME doesn't want you to use them.

It seems major Linux desktop devs finally are [coming up with a modern standard for this](https://pagure.io/fedora-workstation/issue/264). But probably takes some more years until it's fully hammered out and implemented in the major GUI toolkits.

@lakoliu Apart from support for something like "AppIndicators", another viable way to implement this might be via a *persistent notification* (displayed as long as time tracking is active) showing the tracked time plus task info etc. You could even add a "stop" button to stop time tracking directly via the notification.

I tried to find some documentation on this subject but didn't really succeed. There's a [GNOME notifications tutorial](https://developer.gnome.org/documentation/tutorials/notifications.html) and the gtk4 crate [seems to provide support to emit (and withdraw) notifications](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/?search=notification). But I'm not sure whether it's currently possible to show really dynamic content in a notification (the time tracked up until now). A workaround could be to regularly update the notification (say every 5min). Or simply omit the tracked time until GNOME adds some proper API for this.

**Comment by lakoliu** [comment]
I personally wouldn't want a persistent notification but I will look into making it a setting if that is something many people would want.
