### ISSUE TITLE
Sync with an online service

### ISSUE THREAD

**Issue by 12people** [lakoliu/Furtherance#29]
It'd be great if Furtherance could provide the option of syncing with an online service, for easier cross-device use.

[Kimai](https://github.com/kevinpapst/kimai2) is a free and open-source online tracker that also allows self-hosting. It has an [open API](https://demo.kimai.org/api/doc) that could be used for this integration.

**Comment by lakoliu** [comment]
That's interesting, I hadn't thought about that. Part of what I love about Furtherance is not having to sign in or create an account to use it, but I can also see the value in adding the option to sync across devices. Thanks for the suggestion, I'll keep it in mind!

**Comment by Gotterbild** [comment]
@lakoliu 
One of the ways to implement online sync is to just allow to save app's DB into a custom location.

So, user just saves it into a folder that syncs to GDrive/Dropbox/Nextcloud/You-name-it and gets the online sync. 

However, the proper and private implementation of this option would require some sort of protection by encryption. Probably even with a password.

**Comment by 12people** [comment]
Saving a DB to a folder is definitely an okay option. For me personally, it would make more sense as a backup rather than a sync option, as it would inherently not be able to elegantly deal with version conflicts.

I think encryption could be left to the service one is using (e.g. services like ProtonDrive, MEGAsync, Tresorit etc. all offer encrypted storage; NextCloud offers it optionally).

That said, I'd still appreciate sync with an online service like Kimai, to allow for multiplatform use and version conflict resolution.

**Comment by toger5** [comment]
Another option would be to use an open protocol like matrix. There is a matrix rust sdk that could be used to log in and allow everyone to use a private encrypted matrix room to store the data. Each activity could even be saved as an event, so that there are no conflicts even if you track the time with different pc's (each pc would just add the events to the room and furtherance would than add the accumulated time locally). Users could even host their own matrix servers so that furtherance is entirely independent of any hosting provider.

**Comment by lakoliu** [comment]
Just wanted to post an update that the latest version of Furtherance for Windows includes the ability to store the database in a user specified location, therefore making it possible to store it in the cloud for syncing with other devices. All versions of Furtherance (Android, Windows, and Linux) use compatible databases.

The next task on the agenda is to bring this feature to the Linux app.

**Comment by lakoliu** [comment]
Commit #29 makes it possible to change the database location in Furtherance for Linux, as well as import an existing database or backup the current database. 🥳This change will be in the next release.

**Comment by rickykresslein** [comment]
After 2.5 years, I'm excited to announce that Furtherance finally has cross-device syncing. [Furtherance Sync](https://github.com/unobserved-io/furtherance-sync) can be self-hosted, or you can subscribe to the fully managed service for $5/month [here](https://furtherance.app/sync). Thank you so much for your extreme patience everyone! I hope the wait was worth it.
