### ISSUE TITLE
Add colors to button

### ISSUE THREAD

**Issue by Aurnytoraink** [lakoliu/Furtherance#31]
Use libadwaita's color properties to enhance the appearance of the user interface.
For example, you can add this CSS classes:
- `destructive-action` for all delete buttons
![image](https://user-images.githubusercontent.com/28545669/164117547-0a753581-2569-4ede-8d1b-6415d219bd1c.png)
- `suggested-action` for the start button (which can be colored only if the name task is set)
![image](https://user-images.githubusercontent.com/28545669/164117841-6d639e27-c2fa-4a6f-9c28-9c59042dc783.png)

**Comment by lakoliu** [comment]
Thank you. I've also realized I need to do this for the delete buttons but haven't gotten to it yet. I hadn't thought about the start button, which is a good idea. Thanks for the push, I'll get started right away :)

**Comment by lakoliu** [comment]
These changes have been made and they will be in the next release. Thanks again for the suggestion!
