### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by mrjrozycki** [lakoliu/Furtherance#32]
Hi
I just want to tell I really like the product, I was wondering if u can add some visualization like a pie graph or bar graph showing how much time we spent on certain tasks.

Cheers :D

**Comment by lakoliu** [comment]
Hey Jakub, thanks for the suggestion! That is actually something on my to-do list. Right now I'm working on tags (which should be ready soon) and then I will be moving on to a way to display time tracked. I was also thinking about doing a pie chart, with the ability to filter by time, tasks, and tags. I'll let you know here when I've got something! Hopefully it won't be too long.

**Comment by Gotterbild** [comment]
@lakoliu 
Here's screenshots from Top Tracker. I really like how they lay out the info. There's ability to filter and display time in a different manner.

This is one page, it just didn't fit in a single screenshot.
![image](https://user-images.githubusercontent.com/23502743/168772842-0d41ba58-1223-4347-a878-f25e14711a3e.png)
![image](https://user-images.githubusercontent.com/23502743/168773177-2821cbcb-d233-4aa9-811f-1e9ac6a93cf2.png)
![image](https://user-images.githubusercontent.com/23502743/168773129-b20ab1be-d0f9-40a9-8360-a8a9bf6c183b.png)

Activity Log view:
![image](https://user-images.githubusercontent.com/23502743/168773679-8be80f34-971c-4767-a80d-09f753137268.png)

Work Summary view:
![image](https://user-images.githubusercontent.com/23502743/168773914-dd3d8311-ae30-49bf-a1b5-c6c6a29a1a4f.png)

**Comment by toger5** [comment]
Just to give one example here is what I would like (need):
 - Set start end period of a timeframe (one week, one month ...) and see the total time tracked in this timeframe
 - See an overview of the average time spent during multiple timeframes (weeks) how many hours each week/ month ...

**Comment by lakoliu** [comment]
Thanks for that info, Timo. I've been working on this a lot recently and the first iteration is almost ready for release. It's going to cover everything in your first bullet point and a little bit more. As for your second bullet point, average time spent over a timeframe, I really like that idea and had not thought of that. I will put that on the list of improvements to work on once the first rollout is complete.

**Comment by lakoliu** [comment]
"Reports" are now a part of Furtherance v1.4! They aren't as pretty or as feature filled as I hope to make them in the future, but it's a start. I'll leave this issue open as a place to provide ideas and suggestions for future improvements. Thank you everyone who has already provided such great advice!
