### ISSUE TITLE
Pomodoro timer

### ISSUE THREAD

**Issue by pal-ef** [lakoliu/Furtherance#34]
I use Furtherance in conjunction with a timer app so that I can 'block' my studying sessions, it would be awesome to see some timer functionality inside the app. I'm loving the work so far, thanks!

**Comment by lakoliu** [comment]
Thanks for the recommendation! Just to make sure I'm clear, do you mean a countdown timer? So, for example, there would be another window alongside the main Furtherance window with a timer set to 15 minutes that counts down to zero, then notifies you that the time is up?

**Comment by pal-ef** [comment]
Precisely! The idea would be maybe inside the preferences letting the user decide if they want to set up a 'countdown timer/pomodoro timer' functionality, if so they get to set the minutes for the timer. Furtherance would then notify the user when the time's up, stop tracking and let them decide if they want to stop working on the task or continue (as a pop-up/sound/notification).


![Group 1(4)](https://user-images.githubusercontent.com/63682116/164989591-d6fe5119-9bb8-4933-8c88-6ea5a6b87eee.png)
![Group 2](https://user-images.githubusercontent.com/63682116/164989859-bdc02355-7258-463d-8c3b-b479a831f38b.png)

**Comment by lakoliu** [comment]
Cool, I think this is a good idea, I'll add it to the list. Hopefully I can get to work on it soon.

**Comment by lakoliu** [comment]
I've just added this feature and it will be released with version 1.1.3 :)
