### ISSUE TITLE
Unable to translate some strings

### ISSUE THREAD

**Issue by rene-coty** [lakoliu/Furtherance#38]
As I wanted to contribute to the translation of the app, I realized that some strings in the Preferences window are not translatable, because they don't exist in the .pot file... Therefore they only appear in English.
As you can see in the screenshot below (of the French version of the app), this concerns the last two parameters of the Preferences window (Tags and Pomodoro + the "Timer" label)
![Capture d’écran](https://user-images.githubusercontent.com/95506494/166476953-efee2171-8a90-4d8d-a95c-4e5abcd99e3f.png)

**Comment by lakoliu** [comment]
Yep, I completely forgot to update the POT file when I added the Pomodoro timer. Thank you, I will get this updated as soon as I can.

**Comment by lakoliu** [comment]
The .pot file has now been updated by @musiclover382 in commit 1c71c84
