### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by jimmac** [lakoliu/Furtherance#4]
Such a lovely app deserves a nice visual identity in the form of a well executed app icon.

**Comment by jimmac** [comment]
Let's kick things off with a concept/metaphor that fits and thanks to the colorful nature of pie charts it could have a decent visual punch.

![Furtherance](https://user-images.githubusercontent.com/14821/161016119-a7cdffd8-beb4-485f-b0d8-a1110c57d151.png)

**Comment by lakoliu** [comment]
My initial reaction was that I kind of like the current logo, but after seeing your concept I'm ready to throw the current logo away! I really like what you've drawn there. Unfortunately, I don't have the Inkscape skills to make it a reality. If you have the time I would love to see a vector of that. I'd like to stick with the yellow color that Furtherance uses currently, but I'm open to other ideas as well.

**Comment by jimmac** [comment]
I opened the issue with the intent to design the icon. Making yellow the dominant color is not a problem.

**Comment by lakoliu** [comment]
Thank you, that's very generous of you, I really appreciate it! Can't wait to see what it looks like.

**Comment by jimmac** [comment]
![Initial Fullcolor Concept](https://user-images.githubusercontent.com/14821/161040020-9fe7b996-25e1-4a9f-b87c-f105d249e5a0.png)

**Comment by lakoliu** [comment]
That looks great! Again, thank you so much for taking the time to do this. I really like the look of the timer inside, and the one wedge of the pie chart sticking out. The only thing I'm not sure of is the colors. It looks a bit like a Google icon with those colors to me. Maybe I was wrong in suggesting the yellow. What would you have gone with if I hadn't suggested yellow?

**Comment by lakoliu** [comment]
I like that yellow one, but now when I look at them all together I'm liking the first one the best 😂. I'm still unsure. I think I need to take some time to take them in. I really like the idea, I may just still be somewhat attached to my original icon since I spent time designing it, even though it's definitely not the best.

**Comment by jimmac** [comment]
The color alternatives are part of the 'source' SVG, we can always iterate later.

**Comment by lakoliu** [comment]
So I've asked 6 people their opinions on the icons and all 6 preferred the "F". That's definitely not to say it's a great icon, but I think we still have some work to do here. Perhaps we should come up with some new ideas to try. I'll be tied up in other things the next few days, so I'll be thinking about this over that time. I'm certainly not asking you to invest hours of your time in this, but if you have the time and desire your skills are much appreciated.

**Comment by GuillaumeAmat** [comment]
For what it's worth I tend to prefer @jimmac's proposition, as it improves the app instant discoverability/understandability, and it is more aligned with GNOME style/guidelines (e.g.: I'm a GNOME user).

Though, the Furtherance name suggests that something is ongoing, rather than it is complete. So, maybe a Gantt inspired representation would better fit the app than a complete/finite circle? :shrug:

**Comment by lakoliu** [comment]
Cool, thanks for the input! Which of the color variants from @jimmac do you like most?
I like that idea, though I have to admit I had to look up Gantt! I would love if we could modify it a bit to incorporate the Furtherance name/meaning.

**Comment by GuillaumeAmat** [comment]
I prefer the colorful/first one :ok_hand: 

But I'm curious to see it applied to the bolder shape of the sketch. I like that it's more asymmetric and that's the "highlighted" part has more volume.

**Comment by jimmac** [comment]
If you want to go back to the drawing board and avoid using a metaphor to your advantage, here's a sketch of something following the style guidelines but center around the existing F logo.![image](https://user-images.githubusercontent.com/14821/161381881-bacbc168-228d-452f-b5c1-87259c180a39.png)

**Comment by lakoliu** [comment]
I would like to use a metaphor, and I do like the first one. I agree with @GuillaumeAmat that I like the bolder "pie piece" as shown in the first sketch. I also like the F you've drawn. What if we added a bit of a metaphor to that, such as clock hands?

**Comment by bertob** [comment]
Here's an attempt at a more literal metaphor:

![image](https://user-images.githubusercontent.com/1908896/161535163-4534f3aa-7dd6-47e6-b254-e87ee08d6997.png)

**Comment by lakoliu** [comment]
Thanks for getting in on this @bertob. I REALLY like that icon! I would still like to see what the F @jimmac made looks like with some clock hands on it, but I'm thinking we may have a winner with this one. I especially like that task list in there. Very cool, thank you!
