### ISSUE TITLE
Add a way to retroactively log a time period

### ISSUE THREAD

**Issue by johanfleury** [lakoliu/Furtherance#42]
Currently Furtherance supports restarting a task (i.e. tracking a new time period for an existing task) by starting the timer with the exact same title as an existing task, but this is a bit cumbersome when using long task names as there is no way to select a task title for copy/pasting without going all the way down to the time period edition view.

It would be great to have a “play” button (alongside the task or in the task view) to start logging time into an existing task. It would also be great to be able to retrospectively log time from the task view pane (i.e. a “plus” button that would show the task edit view for a new time period).

**Comment by lakoliu** [comment]
Hi! Right now Furtherance does allow you to duplicate a task by right-clicking it. It is listed in the instructions the first time you start the app, but never again, so I know it isn't very clear and I've been thinking about how I can make sure users know about this feature. 

I have thought about adding a button, and it might come in the future. It was discussed in Issue #12. 

I think you have a good idea with adding a past log with a + button, so I will consider adding that. I will leave this Issue open for now to get more feedback on a button to retroactively add tasks. Thanks for your input!

**Comment by lakoliu** [comment]
Furtherance now has an "Add Task" button. It will be in the next release.
