### ISSUE TITLE
Tracked time lost when device shuts down

### ISSUE THREAD

**Issue by Gotterbild** [lakoliu/Furtherance#45]
Yesterday I was tracking time via Furtherance and then my laptop shut down due to low battery.

When I've came home and plugged the laptop in, I found out the tracked time was lost. There was no record at all.

I think it will be good if app automatically saves the currently tracked time every minute or at least every 5-10 minutes, so the record is not lost in case device shut down.

**Comment by lakoliu** [comment]
That's a good idea, I will work on this as soon as I can. Unfortunately my motherboard is being replaced by Dell right now, so I don't have a computer for about 2 weeks.

**Comment by lakoliu** [comment]
My little netbook I have as a backup was able to handle Gnome Builder, so I've now added an Autosave feature. It can be turned on and off in Preferences and minutes between autosaves can be adjusted as well. If Furtherance shuts down improperly (crashes, laptop dies, app closed before stopping timer, etc.) then the autosave will be written to the database the next time Furtherance is opened and a notification will be displayed. 

This feature will be in the next release. Thanks for the suggestion!

**Comment by Gotterbild** [comment]
@lakoliu 
Thanks! 👍
