### ISSUE TITLE
Unable to translate some strings

### ISSUE THREAD

**Issue by rene-coty** [lakoliu/Furtherance#48]
With the 1.3 release, an autosave option was added to the app menu, but the text can't be translated (it only appears in English), since the .pot file hasn't been updated... could you change it ?
Other useful changes to add to .pot file would be the addition of the changelog of the 1.3 release + the ability to translate the month name on the main page... (these are pure suggestions to improve the use of the application by everyone)

**Comment by lakoliu** [comment]
Yes, sorry about that, I will get it updated as soon as possible. Thank you for pointing this out.

**Comment by lakoliu** [comment]
Just updated the .POT file with commit 2eebeec. As soon as a couple translations are updated I will create a release with the updates.
