### ISSUE TITLE
Double clicking on the edit button causes the window to be moved to the back

### ISSUE THREAD

**Issue by r3pll** [lakoliu/Furtherance#51]
If you click edit button or near more than once, the new window moves to the back. Only Esc helps to close window

**Comment by lakoliu** [comment]
Thank you for letting me know about this, I'll get it fixed as soon as I can.

**Comment by lakoliu** [comment]
I've fixed this, as well as the same issue with several other dialogs. Thank you again for bringing this to my attention.
