### ISSUE TITLE
French home screen is truncated on a Librem5

### ISSUE THREAD

**Issue by azmeuk** [lakoliu/Furtherance#52]
Here is how Furtherance looks in French on a Librem5. The sentences are truncated and the whole interface looks misaligned. As a consequence the burger menu is hidden:

![2022-06-01-102215](https://user-images.githubusercontent.com/60163/171449535-42d602ff-b0bc-478e-8ff0-ca17b1aae684.png)

**Comment by lakoliu** [comment]
Thank you for bringing this to my attention. Unfortunately I don't have a Linux phone to do any testing on, but I will look into this and see if there is anything I can do.

**Comment by azmeuk** [comment]
@lakoliu you won't fix this because you have not the device to test a solution? If this is the reason, is there anything I can do to help?

**Comment by lakoliu** [comment]
Yes, I don't have a plan to fix it because I have no way of testing it. If you would like to submit a fix I will happily merge it. It's still on my list, but I just don't know what I can do until I have a way of testing it. I don't have any experience building for Linux phones. Sorry!

**Comment by lakoliu** [comment]
I will open this back up. Hopefully there is someone out there with Rust experience and a Librem phone! It would be great if we could get this fixed.

**Comment by lakoliu** [comment]
This should be fixed in the next release. I still don't have a phone to test it, so please let me know if it is not. Some of the windows may still be cut off, and I am working on a way to fix that, but the main page should work.

**Comment by azmeuk** [comment]
I confirm this is fixed!
