### ISSUE TITLE
Localize the three letters for months / localize date format

### ISSUE THREAD

**Issue by musiclover382** [lakoliu/Furtherance#54]
Would it be possible for furtherance to use some kind of gnome widget to choose dates?

Otherwise, we should localize at least the month letters so that international users don’t get confused

**Comment by lakoliu** [comment]
That's a good idea, but localizing the months seems like it may be difficult. I'm not sure if the Rust chrono::DateTime crate accepts the month in any form besides English, so it would need to detect and translate the user's input to convert it. I'm not aware of any GTK widget to choose the dates, but I will look into it.

**Comment by lakoliu** [comment]
I couldn't find a crate to help with localizing the months, so I changed the format to be a localized version of MM/DD/YY (for example, in most of the world it will read DD/MM/YY, but in the US it will be MM/DD/YY).

**Comment by musiclover382** [comment]
Awesome, thanks!!

**Comment by musiclover382** [comment]
An update on this: I still see MM/DD/YY even though in Italy we use DD/MM/YY.

Plus, the problem recurs (in a much less problematic way) in the main window to display the date tasks are done.

idk if there is something we can do about it 🤷

**Comment by lakoliu** [comment]
You're right, I completely forgot about changing it in the task history list! I will get that changed as well. As for the first part, That's very weird, I'm going to need to look into why it is doing that. I'm using the %x formatter of chrono::DateTime to do it, so I wonder if it is an issue with that. I'll need to check their GitHub to see if there are any known issues, or if it is something I'm doing wrong.

**Comment by lakoliu** [comment]
Update 1: I was able to localize the date headings in the task list, so those should now show correctly in Furtherance v1.5.1. They should show up in whatever language your computer is set to. 

Update 2: Unfortunately there is no way at this time to parse localized DateTime strings, so there is no way for me to localize the date in the task editor dialog window. I will be keeping an eye on this to see if it changes (hopefully it will in the future).

I'm going to close this issue for now since there is nothing more I can do, but I will keep my eye out for any changes I can use to make this happen.

**Comment by salim-b** [comment]
> Unfortunately there is no way at this time to parse localized DateTime strings, so there is no way for me to localize the date in the task editor dialog window.

@lakoliu If that's the case, it would be nice to display the date in ISO 8601, i.e. as YYYY-MM-DD. That would be less confusing for non-English speakers.

Even better would be to use a system-native date-time selection dialogue, I guess. That way no need to parse strings of (localized) datetimes (you could still localize the *presentation* of the datetimes, but no need to inverse that operation). I have no clue about GTK4, but a quick web search led me to [`GtkCalendar`](https://developer-old.gnome.org/gtk4/stable/GtkCalendar.html), maybe something you could use?

Apart from that, it might be worth to have a look at the [icu](https://docs.rs/icu/latest/icu/) crate which features a dedicated [`datetime` module](https://docs.rs/icu/latest/icu/datetime/index.html). From my experience (none with Rust), ICU is the way to go when trying to localize dates/times in a portable way.

**Comment by lakoliu** [comment]
Thanks for your input @salim-b. I agree, the date format should be changed. I will reopen this and get on that, making them ISO 8601 format. 

Unfortunately, the `GtkCalendar` widget is just too large for what I'm going for and there is no way (as far as I can find) to create a date picker widget like often is in web apps where you can just click the date box and then a calendar pops out. I also looked into `icu` and as far as I can tell there is no way to localize or parse localized DateTime strings.

**Comment by lakoliu** [comment]
I just changed everything over to ISO 8601 format (except the main page, which is already localized) in commit 4da122a.
