### ISSUE TITLE
Host translations on Weblate

### ISSUE THREAD

**Issue by musiclover382** [lakoliu/Furtherance#55]
I watched the [requirements for free hosting](https://hosted.weblate.org/hosting/) on Weblate and Furtherance seems to meet them all.

**Comment by lakoliu** [comment]
Thank you! When I get a chance I will look into moving Furtherance's translations to Weblate.

**Comment by lakoliu** [comment]
Translations should now be possible on [Weblate](https://hosted.weblate.org/projects/furtherance/translations/)
