### ISSUE TITLE
Today/Yesterday should update automatically if the app is running and a new day starts.

### ISSUE THREAD

**Issue by toger5** [lakoliu/Furtherance#56]
Currenlty the app only updates if a new time track event is added or the app is restarted. It should also update the titles for yesterday and today if the app is running in the background and a new calender day starts.
# Situation
I have recorded a 2hour activity yesterday. I start furtherance today:
## expected
I see:
```
Yesterday
2hours
```
## current behaviour:
In the list I see: 
```
**Today**
2hours
```
When I record a new activity (for example 15min) it shows 
```
Today
15minutes
```
```
Yesterday 
2hours
```

**Comment by lakoliu** [comment]
I'm sorry, I don't think I understand? This seems like the expected behavior. If you had 2 Hours recorded yesterday and 15 mins today then it should show it exactly as you say it does.

**Comment by lakoliu** [comment]
Did you leave the application open overnight, or past midnight, when this happened? At the moment there is no feature for the application to automatically refresh the list. It is only refreshed when something happens, like a task is saved or a setting is changed. Could that have been the issue?

**Comment by toger5** [comment]
Yes I did

**Comment by toger5** [comment]
Not having a refresh mechanism definilty souds like the problem. I just tried restarting the app. that also fixes the issue.
I rephrase the issue title to represent the feature I think would improove the app.

**Comment by lakoliu** [comment]
I will look into this but I'm not sure it will be worth the processing power to have a loop constantly checking for time of day.

**Comment by toger5** [comment]
Can you use a cron job? That should not add additional processing power right?

**Comment by lakoliu** [comment]
I just spent some time trying to create a cron job to do this, but I've been unsuccessful. If someone else has the expertise to do this, I'm happy to merge the code. Thanks for the recommendation, I'll keep it on the list until it is solved.
