### ISSUE TITLE
GLib-GIO-ERROR **: Settings schema 'com.lakoliu.Furtherance' is not installed

### ISSUE THREAD

**Issue by gapplef** [lakoliu/Furtherance#58]
I'm trying to compile furtherance in docker container.
After successfully compiled and installed under my home directory, furtherance can't start.
What I need to do to fix the problem?

**Comment by lakoliu** [comment]
I'm sorry I'm not very familiar with Docker so I'm not sure how to fix this, but from that error it sounds like it could be a permissions error not allowing Furtherance to create its settings schema.

**Comment by lakoliu** [comment]
Here are a couple resources that seem to have resolved this error. Please let me know if one works for you.

https://stackoverflow.com/questions/16522932

https://darrengoossens.wordpress.com/2018/03/12/glib-gio-error-settings-schema-somethingorother-is-not-installed/

**Comment by gapplef** [comment]
I don't know what the `settings schema` is. I can find the `com.lakoliu.Furtherance.gschema.xml` under the install location `~/.apps/furtherance/share/glib-2.0/schemas/`. I can compile it with `glib-compile-schemas`, but still can't launch furtherance.


I'll explained what I have done.
I don't want to install all the development dependencies, so I use container to do the compile:
1. launch the ubuntu container in interactive mode(`-it`) and mount the furtherance source code(`-v`):
`docker run --rm  -it -v  ~/Downloads/Furtherance-main:/app  -w /app/build  ubuntu:jammy`
2. installed the necessary dependencies:
`apt-get update && apt-get install --no-install-recommends gettext ca-certificates pkg-config appstream-util desktop-file-utils meson cargo libsqlite3-dev libdbus-1-dev libglib2.0-dev libgtk-4-dev libadwaita-1-dev`
3. specified the install location:
`meson --prefix=/home/julian/.apps/furtherance  ..`
4. `ninja`
5. `DESTDIR=/app/out  ninja install`
6. after compiled successfully inside the container, I copy the installing files to the install location on the host machine.

I expected all the runtime dependencies already installed on my ubuntu 22.04 + gnome 42 system, maybe I miss some runtime dependencies?

**Comment by lakoliu** [comment]
I will try to recreate this error when I get a chance, but for now I'm not skilled enough in Docker to be much help. I know Furtherance works when it is compiled outside of a container, so the container must be preventing Furtherance from access the settings files it needs for some reason.

**Comment by gapplef** [comment]
ok, thank you for your time!

**Comment by gapplef** [comment]
I tried the same process with virtual machine(gnome boxes), the same error still exist.
Seems it's not the container's fault.

**Comment by gapplef** [comment]
I find out how to fix the problem, it has nothing to do with container. The error is due to the custom of install location. 
Although I set the install location to `~/.apps/furtherance`, the program still looking for data in default `XDG_DATA_DIRS`, not the  `~/.apps/furtherance/share`. I don't know if this is the expected behavior, but after set `XDG_DATA_DIRS=$XDG_DATA_DIRS:$HOME/.apps/furtherance/share` the error was fixed. I found the solution in [here](https://github.com/phw/peek/issues/238).

---
But I get another error: `Gdk-Message: Error flushing display: Protocol error`.
This seems related to my Wayland+NVIDIA setup, as the same compiled files can run without problem inside the virtual machine. Is there any quick fix for this, or should I open another issue for this?

**Comment by lakoliu** [comment]
Okay, thank you for that! I will look into setting a default location in case XDG_DATA_DIRS is not found. I really appreciate you letting me know about this.

Please open a new issue for the new error message and I will try to look into it. Off the top of my head I'm not sure of the cause.

**Comment by lakoliu** [comment]
After looking more into this I realized that even if I set an alternate default directory then it would only be correct for some users. I don't think it's practical to create an alternative, so for now if a user is doing something different like installing Furtherance in a Docker container, they will need to set the XDG_DATA_DIRS environment variable manually. Thanks for writing this up to let people know how to do that!

**Comment by gapplef** [comment]
Like I have said, it has nothing to do with container. Install furtherance in virtual machine have the same problem. Container is only a temporary development environment that can be throw away once the source file is compiled.

The problem is when set custom install location (`meson --prefix=/path/to/install`), the `XDG_DATA_DIRS` should be `$XDG_DATA_DIRS:/path/to/install/share`. i.e. when the path of executable file located in `/usr/bin`, data file located in `/usr/share`; while when the path of executable located in `/custom/install/path/bin`, data file located in `/custom/install/path/share`.

I am not a developer, so I don't know if the change is practical, but it should be a common case for any application that compiled with a user defined install location, not special to some users.

Anyway, thanks for your patience and really appreciate your time and effort!

**Comment by lakoliu** [comment]
Okay, I'll look into if there is any way to detect if a user changes the install path and change the data directory to that path, but if there is a way I don't know how to do it. If anyone else does please let us know.
