### ISSUE TITLE
"Total time" font color doesn't follow the dark style variant

### ISSUE THREAD

**Issue by GuillaumeAmat** [lakoliu/Furtherance#6]
Tested on GNOME 42, with the global OS dark style setting, and Furtherance v1.0.8 from Flathub.

![image](https://user-images.githubusercontent.com/1179174/161337974-93a903d0-aae9-487a-99d0-ed5f059665c6.png)

**Comment by lakoliu** [comment]
Oh, wow, good catch, thank you! I'll get started on fixing this right away.
