### ISSUE TITLE
Negative time when adding a new task

### ISSUE THREAD

**Issue by r3pll** [lakoliu/Furtherance#63]
I guess it's a bug. It happends when a stop time is before a start time.
![Снимок экрана от 2022-06-07 17-04-59](https://user-images.githubusercontent.com/106473215/172402538-b2b34660-eb60-4e5e-ac05-7865bfb7edea.png)
![Снимок экрана от 2022-06-07 17-23-05](https://user-images.githubusercontent.com/106473215/172404808-ca6dd4f4-526c-4d69-a4da-7eb30a8541f0.png)

**Comment by lakoliu** [comment]
Are you using the latest version of Furtherance? There should be an error message when the stop time is before the start time, and it should not allow the change to happen.
![Screenshot from 2022-06-07 18-02-04](https://user-images.githubusercontent.com/99976966/172414134-903f8754-2562-43bc-b7bd-345cdbe2ecdd.png)
I'm not able to replicate your issue in the latest version of Furtherance.

**Comment by lakoliu** [comment]
Ahhh, okay, yes, you are right, this is a bug. I thought I had implemented a catch for this error but apparently not. Thank you for letting me know, I will get working on it immediately!

**Comment by lakoliu** [comment]
Okay, I just fixed this for the next release (probably coming out tomorrow). Also, the date format will now be XX/XX/XX depending on locale to match commit 37b9ca0.
