### ISSUE TITLE
New icon is off-style

### ISSUE THREAD

**Issue by bertob** [lakoliu/Furtherance#76]
The new icon is unfortunately a step back in terms of style, issues include:

- Weird, non-geometric shape
- Not a physical object
- Clock hands are very thin and dark on a partly transparent background, making them hard to see in the shell
- Generally unclear what it's supposed to be, it's trying to do too many things at the same time in terms of metaphor

The circlular clock with a huge F background could work, but then I'd drop the cutout and just do a regular circular shape and drop the list thing in the background. That said, I don't know what was wrong with the previous alarm clock metaphor, I think that worked quite well as it was :)

![image](https://user-images.githubusercontent.com/1908896/179770665-e5261eac-1747-4db2-aa50-e402342748d2.png)

**Comment by daudix-UFO** [comment]
Fully agree, and also it now don't follows GNOME HIG, previous icon is one of the best icons in my opinion!

**Comment by xscd** [comment]
I have to say I also really liked the old icon. Seemed more in-line with the GNOME HIG.
