### ISSUE TITLE
Set automatic color labels for rough time intervals when a task starts/ ends

### ISSUE THREAD

**Issue by marek-lach** [lakoliu/Furtherance#78]
This could look something like...

![hours_time_tracking_concept](https://user-images.githubusercontent.com/45913977/180613190-e5c0211d-0b2e-4cfd-8d59-4d69adf3add7.png)

While this time duration start/end time could be set for either a single task, or a selection of tasks per a given day. Not necessarily precise, but up to a minute _(like 9:40 AM to 5:00 PM)_, with color differentiated labels next to these intervals: like 9:00 AM - 5:00 PM, if these are set, it could be set to assign #work label, or saved so that the #work label has time intervals from 9:00 AM to 5:00 PM, for example.

The logged information could then be exported into a document (pdf?) per week, or a month, or a quarter of a year...

**Comment by lakoliu** [comment]
Sorry, I'm not sure exactly what you mean. Could you maybe use a screenshot of Furtherance and then edit it to show what you would want to have a different color?
