### ISSUE TITLE
[Suggestion] update meson post-install mechanism

### ISSUE THREAD

**Issue by CaptainJawZ** [lakoliu/Furtherance#79]
Hello! I've been working on porting Furtherance into a Nix/NixOS package. I'm fairly new when it comes to development and builds, but it was suggested to me by the maintainers of NixOS to pass on the suggestion (as I understand it) that Meson has a new post-install mechanism for gnome, which makes the ../build-aux/meson/postinstall.py obsolete. 

apparently it's only a matter of deleting said script and adjusting the meson.build with a couple new lines as suggested on here: 
https://gitlab.gnome.org/GNOME/d-spy/-/merge_requests/6/diffs

Sorry if I'm bad at explaining it, I hope it makes sense!

**Comment by jtojnar** [comment]
@winterqt’s patch is here: https://gist.github.com/winterqt/a596b439016e65b7cceee3a299392128

**Comment by winterqt** [comment]
I've PR'd a more robust version of the linked patch at #80.

**Comment by lakoliu** [comment]
Awesome! I've recently become quite interested in Nix, so this is super cool to hear. I've merged @winterqt's PR so hopefully you can get it working now :) Thanks everyone!
