### ISSUE TITLE
total hours per task in report

### ISSUE THREAD

**Issue by tobehn** [lakoliu/Furtherance#82]
When i export data as report i would like to see a field for the total amount of time tracked per task either idealy format hh:mm.
Basically _stop_time_ minus _start_time_ .

By that i can easliy filter and sum up certain times in the report.

I was not able to convert the timestamp in the current CSV to become epoch nor do any calculations with it

**Comment by lakoliu** [comment]
I believe this feature is already in Furtherance, unless I don't understand what you mean. When you generate a report the duration of each task is listed to the right of the task. That is the total amount of time tracked for that task during the time period you've selected. Does that resolve your issue, or did you mean strictly in the CSV Export?

**Comment by tobehn** [comment]
Sorry, I was talking about the CSV-Export.

I realised it in the GUI Report feature now.

**Comment by lakoliu** [comment]
Yeah, the CSV export is just a straight printout of the database essentially. If you want formatted data with calculations like total time spent you will need to use the Generate Report feature.
