### ISSUE TITLE
Prefill original name when editing task name

### ISSUE THREAD

**Issue by 12people** [lakoliu/Furtherance#86]
Sometimes, I just want to add a tag to an existing task name.

Right now, to do that, I have to edit the task name, retype the original task name, and then add my tags.

Instead, I'd just like to go edit the name, have the original name prefilled, and be able to just easily append tags.

Alternatively, tags should be edited via a separate UI element

**Comment by lakoliu** [comment]
The "Edit Task" windows will now have the current task name with tags pre-filled in the next release.

**Comment by 12people** [comment]
Awesome, thank you!
