### ISSUE TITLE
[Feature request] Implement new About Window

### ISSUE THREAD

**Issue by rene-coty** [lakoliu/Furtherance#87]
Since the introduction of libadwaita 1.2 (with some of its changes being backported to libadwaita 1.1) there is a new About Window widget which looks much more polished and comprehensive than GtkAboutDialog. Since some of the core Gnome apps already integrate this change, it would be great to see it arriving in the next releases of Furtherance :)...
(this is just a pure aesthetic suggestion)

**Comment by lakoliu** [comment]
Thank you for the suggestion! I do plan on doing this, but unfortunately libadwaita-rs 1.2 still hasn't been released. There are a couple of features I'm really looking forward to with this release, the about window being one of them. As soon as it is released I will make this change.
