### ISSUE TITLE
Add a filter for last week's report

### ISSUE THREAD

**Issue by Sunling472** [lakoliu/Furtherance#97]
It would just be convenient if, when requesting a report, there would be a filter for last week at once.

**Comment by lakoliu** [comment]
Hey, thanks for your suggestion. How would this differ from the current "Past week" option? Would it be the previous Sunday back to the Sunday before that?

**Comment by Sunling472** [comment]
@lakoliu 
Hi, I may have misunderstood something, but as far as I can see there is a filter for the last week, that is, for the current one, and I mean the last one, that is, from the 17th to the 23rd.

Yes, I'm sorry if I formulated it incorrectly, it's just that English is not my strong point, I use a translator.

**Comment by lakoliu** [comment]
No worries, that's what I thought, just wanted to be sure. I am happy to add this but I'm worried it will be confusing. I need to figure out the correct language to make sure people know the difference. I'm not sure if "Past week" and "Last week" are clear enough. Any suggestions?

**Comment by Sunling472** [comment]
Well now I'm using "toggle track", there it looks like this:
![image](https://user-images.githubusercontent.com/80397339/198105595-fb7b3788-2b23-4c59-a8f9-2981d952a63f.png)
![image](https://user-images.githubusercontent.com/80397339/198105775-f75baffd-cc76-43dc-a9a9-7c35a3348fe7.png)

**Comment by lakoliu** [comment]
Okay, I think that could work. I will go ahead and add This Week and Last Week options, and change the current "Past Week" to "Last 7 days" when I get a chance.

**Comment by lakoliu** [comment]
I just added these options in commit c7d283c. There is also the option now in preferences to set whether the week starts on Sunday or Monday. Thanks for your patience! This will be in the next release.
