### ISSUE TITLE
Update today's daily sum while timer is active

### ISSUE THREAD

**Issue by DamnedElric** [lakoliu/Furtherance#99]
It would be really useful to be able to see the total duration for "today". Unfortunately, Furtherance only shows the current timer and the sum of the previous timers for the day, but not the sum of the two. This makes it hard to tell how much time was worked "today".

![sums](https://user-images.githubusercontent.com/60551689/209144564-f9dc9e9c-6a73-46ab-a37a-06bafcc6903c.png)

Looking at the code, it seems like build_task_list could be made to do this, but it's currently only called on startup and on task save.

**Comment by lakoliu** [comment]
I just added this in 3cbbabd. Thanks for your patience! It is off by default, but you can turn it on in the settings. It will be in the next release.
